package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"Menu_Service/graph/model"
	"context"
	"fmt"
)

// FindBaseByID is the resolver for the findBaseByID field.
func (r *entityResolver) FindBaseByID(ctx context.Context, id string) (*model.Base, error) {
	panic(fmt.Errorf("not implemented: FindBaseByID - findBaseByID"))
}

// FindSizeByID is the resolver for the findSizeByID field.
func (r *entityResolver) FindSizeByID(ctx context.Context, id string) (*model.Size, error) {
	panic(fmt.Errorf("not implemented: FindSizeByID - findSizeByID"))
}

// FindToppingByID is the resolver for the findToppingByID field.
func (r *entityResolver) FindToppingByID(ctx context.Context, id string) (*model.Topping, error) {
	panic(fmt.Errorf("not implemented: FindToppingByID - findToppingByID"))
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
