// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AvailablePizzaSelection struct {
	Bases    []*Base    `json:"bases"`
	Sizes    []*Size    `json:"sizes"`
	Toppings []*Topping `json:"toppings"`
}

type Base struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Price float64 `json:"price"`
}

func (Base) IsEntity() {}

type Query struct {
}

type Size struct {
	ID         string  `json:"id"`
	Name       string  `json:"name"`
	Multiplier float64 `json:"multiplier"`
}

func (Size) IsEntity() {}

type Topping struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Price float64 `json:"price"`
}

func (Topping) IsEntity() {}
